### PR TITLE
fix: build container beside amd64 also for ARM

### PR DESCRIPTION
**Pull request by genofire**
i also update base-container from `rust:buster` to `rust:bookworm` - we have to test the new libssl before release it

---

hate github - where is my checkbox, that this MergeRequest has to squash-merge ?

### CODE REVIEW

**Comment by p1gp1g** [comment]
I've started to move mollysocket to mollyim organisation !

I have edited the container recently, it may help : https://github.com/mollyim/mollysocket/commit/c8fc7aab45e8a47fad13b9b46fd7ec789954b26b

**Comment by genofire** [comment]
there appears a 404, i am not able to see that repo.

cool that it merged clother together :)

**Comment by p1gp1g** [comment]
Indeed it is in private, I m asking to change the visibility :)

The commit does that :
```
-    apt install -y libssl1.1 libsqlite3-0
+    apt install -y openssl libssl-dev ca-certificates libssl1.1 libsqlite3-0

**Comment by p1gp1g** [comment]
I'm merging it, I will add it to the other repo when the visibility changes.

BTW:
- It would be nice to upload the builds on releases
- About the helm repo, do you prefer we move it to mollyim org or to your own profile (then we will refer it in MollySocket's readme) ? I guess MollySocket org will be closed

**Comment by genofire** [comment]
i believe it would be nice, to have that next to or in mollysocket.
so maybe the https://github.com/mollyim/mollysocket-helm whould be nice.

---

oh yes, but i do not know yet how. normally i would use [semantic-release](https://semantic-release.gitbook.io) (on gitlab, but also work on [github](https://github.com/semantic-release/github)).

It is possible to select there `assets` which are uploaded, too.
but therefore automatically create release based on convention-commits and could/should not use any manualle release or version-tagging.
If you like it, i will develop an github-workflow for release


i start something here #20

**Pull request merged**
