### PR TITLE
Deployment in Kubernetes (and build an image for it)

### PR DESCRIPTION
**Pull request by genofire**
- Container image
  - for me only a debian based image works (distroless has no library for sqlite + alpine segfaulted on running -> as comment below, how i build an image) 
  - CI: will upload in githubs registry 
- Helm Chart
  - is an default way to deploy in Kubernetise
  - CI: will generate automaticaly new version (git-tag) and publish in gh-pages / github page (maybe in an extra repo because of auto tagging ...)
  - i will add an ServiceMonitor and maybe an Grafana-Dashboard after #3

### CODE REVIEW

**Comment by genofire** [comment]
Failed alpine Containerfile:
```Containerfile
FROM docker.io/rustlang/rust:nightly-alpine as builder
WORKDIR app
RUN apk update \
    && apk add musl-dev openssl3-dev sqlite-dev
    
COPY . .
RUN cargo build --release --bin mollysocket


FROM docker.io/alpine as runtime
WORKDIR app
RUN apk update \
    && apk add sqlite-libs 

COPY --from=builder /app/target/release/mollysocket /usr/local/bin/
##
# mollysocket connection list
# Segmentation fault (core dumped)
#
ENTRYPOINT ["/usr/local/bin/mollysocket"]
```

**Comment by genofire** [comment]
PS: It is running under https://mollysocket.sum7.eu - for tries - not sure how long and public (depends on, if i could monitor it well and "hacker" usage)

**Comment by p1gp1g** [comment]
Thanks, It looks good to me

**Comment by p1gp1g** [comment]
Acutally, it seems there are 2 issues:
* It creates a release even if the event wasn't a tag/release
* The tag is "mollysocket-0.1.0" and I'd like keeping "0.1.0" (That point is less important)

**Comment by p1gp1g** [comment]
@genofire: I highlight you in case you don't receive a notification with the previous comment, since it is already merged

**Comment by genofire** [comment]
Yes thats the Helm part (and the github actions).
It takes the chart Name and these announced version:
See `charts/mollysocket/Chart.yaml` that is the reason why i make the suggestion to put it into an extra repo. (So maybe take just the first commit for building the container).

**Comment by p1gp1g** [comment]
I've missed that. It is probably possible to run this action on new release and not create a new release at runtime. I'll revert the 2nd commit for now then.

**Pull request merged**
